### ISSUE TITLE
auth 中间件没有吗？

### ISSUE THREAD

**Issue by gopkg-dev** [go-kratos/gateway#211]

**Comment by dagehuifei** [comment]
这个根据自己的需要实现就行吧

**Comment by gopkg-dev** [comment]
> 这个根据自己的需要实现就行吧
也没有个文档,想用不知道咋用,要自己写中间件吗

**Comment by jkwang-a** [comment]
@dagehuifei 我是写了个 jwt的中间件，但是网关配置文件填写后识别不了，不知道哪里出问题了

![image](https://github.com/user-attachments/assets/85858653-c503-4a92-b990-f1d56ef26aee)
![image](https://github.com/user-attachments/assets/26be901b-d18b-4091-962a-abe5d75da9ac)

识别不了 写的这个 jwt

**Comment by jkwang-a** [comment]
@gopkg-dev 你写的auth 中间件 ，gateway 能识别到吗？
