### ISSUE TITLE
HTTP2 stream error: stream ID x; PROTOCOL_ERROR

### ISSUE THREAD

**Issue by liuxp0827** [go-kratos/gateway#6]
curl --location --request POST 'http://127.0.0.1:8080/helloworld.Greeter/SayHello' \
--data-raw ''
![image](https://user-images.githubusercontent.com/4446722/136883535-f1a44497-6a18-4192-add7-d50062c7db3a.png)

**Comment by tonybase** [comment]
目前支持 http -> proxy -> http，grpc -> proxy -> grpc，要是直接http -> proxy -> grpc 需要开发转换插件才可以

**Comment by liuxp0827** [comment]
> 使用的init分支的最新代码吗？

是的 我这边是需要http -> proxy -> grpc这样的代理 楼上的老哥说需要开发转换插件，目前我是用reflection先用着
